{
 "title": "JMeter Results",
 "description": "Monitor your Jmeter load test in real time with InfluxDB and Grafana.",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Application",
    "label": "Application Name",
    "query": "SHOW TAG VALUES FROM \"jmeter\" WITH KEY = \"application\""
   },
   { "name": "aggregation", "label": "Aggregation Interval", "query": "1s" }
  ]
 },
 "panels": [
  {
   "title": "Success Rate",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 1 - sum(\"countError\")/sum(\"count\") FROM \"jmeter\" WHERE $timeFilter AND \"application\" =~ /^$Application$/ AND transaction = 'all'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"countError\")/sum(\"count\") FROM \"jmeter\" WHERE $timeFilter AND \"application\" =~ /^$Application$/ AND transaction = 'all'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\") FROM \"jmeter\" WHERE (\"statut\" = 'ok' OR \"statut\" = 'ko') AND \"application\" =~ /^$Application$/ AND $timeFilter GROUP BY time($aggregation) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Passed Requests",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\") FROM \"jmeter\" WHERE (\"statut\" = 'ok' ) AND \"application\" =~ /^$Application$/ AND $timeFilter GROUP BY time($aggregation) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\") FROM \"jmeter\" WHERE (\"statut\" = 'ko') AND \"application\" =~ /^$Application$/ AND $timeFilter GROUP BY time($aggregation) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Running Vusers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Running Vusers",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT last(\"maxAT\") FROM \"jmeter\" WHERE \"transaction\" = 'internal' AND \"application\" =~ /^$Application$/ AND $timeFilter GROUP BY time($aggregation) fill(null)",
     "select": [
      [
       { "params": [ "maxAT" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "internal" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$Application$/" }
     ]
    }
   ]
  },
  {
   "title": "Hits/Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Total Hits",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"hit\") FROM \"jmeter\" WHERE \"transaction\" = 'all' AND \"application\" =~ /^$Application$/ AND $timeFilter GROUP BY time($aggregation) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transactional Summary (All Response Time Details are in Seconds)",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\") as \"Total Transactions\" FROM \"jmeter\" WHERE (\"statut\" = 'ok' or \"statut\" = 'ko') AND \"application\" =~ /^$Application$/ AND $timeFilter GROUP BY transaction",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT min(\"avg\")/1000 as \"Minimum\", mean(\"avg\")/1000 as \"Average\", max(\"avg\")/1000 as \"Maximum\", percentile(\"avg\", 90)/1000 as \"90th Percentile\", sum(\"count\") as \"Total Passed\" FROM \"jmeter\" WHERE (\"statut\" = 'ok') AND \"application\" =~ /^$Application$/ AND $timeFilter GROUP BY transaction",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\") as \"Total Failed\" FROM \"jmeter\" WHERE (\"statut\" = 'ko') AND \"application\" =~ /^$Application$/ AND $timeFilter GROUP BY transaction",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Transactions Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Transactions/Second (Pass)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") FROM \"jmeter\" WHERE (\"statut\" = 'ok' AND \"application\" =~ /^$Application$/) AND $timeFilter GROUP BY time($aggregation), \"transaction\" ",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$Application$/" }
     ]
    }
   ]
  },
  {
   "title": "Transactions/Second (Fail)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") FROM \"jmeter\" WHERE (\"statut\" = 'ko' AND \"application\" =~ /^$Application$/) AND $timeFilter GROUP BY time($aggregation), \"transaction\" ",
     "select": [
      [
       { "params": [ "countError" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$Application$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTP Response Code per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_responseCode",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\") FROM \"jmeter\" WHERE \"transaction\"!= \"internal\" AND \"transaction\"!= \"all\"  AND (\"statut\"='ok' OR \"statut\"='') AND \"application\" =~ /^$Application$/ AND $timeFilter GROUP BY time($aggregation), \"responseCode\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transactions Response Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT \"avg\" FROM \"jmeter\" WHERE (\"statut\" = 'ok' AND \"application\" =~ /^$Application$/) AND $timeFilter GROUP BY \"transaction\"",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$Application$/" }
     ]
    }
   ]
  }
 ]
}